Makefile.am: fix build on an external directory
Doing external build of the repository fails due to not finding some
header files:

fatal error: wolfengine/we_internal.h: No such file or directory

This is what happens for example in Yocto, where the packages are not
build in the source tree itself but in an external build directory.

Signed-off-by: Javier Viguera <javier.viguera@digi.com>